version: '3'

services:
    # ingest - listening on port 8084
    lightspeed-ingest:     
        restart: on-failure
        build: Lightspeed-ingest/
        network_mode: host
        ports:
            - "8084:8084"
    
    # react - serves on port 80, needs the wsUrl which is public ip:8080
    lightspeed-react:    
        restart: on-failure
        build: Lightspeed-react/
        network_mode: host
        ports:
            - "80:80"

    # webrtc, defaults to localhost:8080. 
    lightspeed-webrtc:     
        restart: on-failure
        build: Lightspeed-webrtc/
        network_mode: host
        ports:
            - "8080:8080"
            - "65535:65535/udp"